export enum ActionType {
    MOVE_CELL = 'MOVE_CELL',
    DELETE_CELL = 'DELETE_CELL',
    INSERT_CELL_BEFORE = 'INSERT_CELL_BEFORE',
    UPDATE_CELL = 'UPDATE_CELL',

    BUNDLE_START='BUNDLE_START',
    BUNDLE_COMPLETE='BUNDLE_COMPLETE',

    FETCH_CELLS = 'FETCH_CELLS',
    FETCH_CELLS_SUCCESS = 'FETCH_CELLS_SUCCESS',
    FETCH_CELLS_ERROR = 'FETCH_CELLS_ERROR',

    SAVE_CELLS_ERROR = 'SAVE_CELLS_ERROR',
}